### ISSUE TITLE
Show default values for query parameters

### ISSUE THREAD

**Issue by glennsc** [enzonotario/vitepress-openapi#123]
### What would you like?

Query parameters can be assigned default values but these do not seem to appear in the documentation.

### Why is this needed?

It gives the reader information about how the API works.

### Other information

```yaml
Types.PaginationParameters.limit:
      name: limit
      in: query
      required: false
      description: Maximum number of items to return
      schema:
        type: integer
        format: int32
        default: 25
      explode: false
    Types.PaginationParameters.offset:
      name: offset
      in: query
      required: false
      description: The number of items to skip before starting to collect the result set
      schema:
        type: integer
        format: int32
        default: 0
      explode: false
```
