### ISSUE TITLE
Boolean query parameters are not displayed in variable list

### ISSUE THREAD

**Issue by wspeirs** [enzonotario/vitepress-openapi#83]
### Current behavior

This is much like #11 
If you have a query parameter that is a boolean, it will not be displayed in the Variables list; see image.
![Screenshot](https://github.com/user-attachments/assets/0e4b6273-cab3-4dfe-a5e0-058d06216b51)

However, if I change the type to string, it works as expected.

Here is the relevant snipit from the openapi file:

```
    use_csv:
      name: use_csv
      in: query
      required: true
      schema:
        type: boolean
        default: false
        example: false
      description: 'Uses the [legacy JSON](docs/Data-And-Requests/Legacy-JSON-Responses.md) format if ``false``.'
```

### Desired behavior

I would expect this variable to appear (checkbox maybe?), and allow me to set it.

### Steps to reproduce

Just create a OAS with a query parameter of `boolean`
